### ISSUE TITLE
如何去除邮箱验证

### ISSUE THREAD

**Issue by xiandaoyun** [lazy-koala/imgs-upload-srv#42]
您好，我尝试去除邮箱验证，但一直报unauthrized，怀疑redis写入时有问题，但一直没有跟踪到，请问有什么建议么

**Comment by acexy** [comment]
unauthrized代表的是需要用户登录的页面在每次请求会去校验用户登录态相关的数据，数据存储于redis中，根据你描述的问题你需要确认你的redis服务是否正常，客户端是否有权限接入服务端并正常完成读写。
