### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by thankjava** [lazy-koala/imgs-upload-srv#8]
@qazyuan 在页面不刷新的情况下，首先点击上传按钮，出现上传框，选择一张图片，点击上传按钮，若服务器不是在很短时间处理完成将出现一个转圈的过渡画面。待服务器处理完毕后，再次点击上传按钮，出现上传框，选择任意一张图片会立即出现一个转圈的过渡界面并覆盖上传按钮无法点击。

**Comment by qazyuan** [comment]
已修复
